[package]
name = "violetrx-traits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
num-derive = "0.3"
futures = "0.3"
async-trait = "0.1.73"

[toolchain]
channel = "nightly"
